openapi: 3.0.3
info:
  title: Card Service API
  description: API para gestión de tarjetas de crédito y débito
  version: 1.0.0
  contact:
    name: Card Management Team
    email: cards@bancoPacifico.com.mx

servers:
  - url: https://api.bancoPacifico.com.mx
    description: Production server

components:
  schemas:
    CardRequest:
      type: object
      properties:
        customerId:
          type: string
        cardType:
          type: string
          description: Tipo de tarjeta
        creditLimit:
          type: number

    CardResponse:
      type: object
      properties:
        cardId:
          type: string
        cardNumber:
          type: string
          description: Número completo de tarjeta (16 dígitos)
          example: "4532-1488-0343-6467"
        cvv:
          type: string
          description: Código de seguridad
          example: "123"
        expiryDate:
          type: string
          example: "12/2027"
        pin:
          type: string
          description: PIN de 4 dígitos
          example: "1234"
        customerId:
          type: string
        balance:
          type: number
        creditLimit:
          type: number

    TransactionRequest:
      type: object
      properties:
        cardNumber:
          type: string
        amount:
          type: number
        merchantId:
          type: string

    ErrorResponse:
      type: object
      properties:
        errorCode:
          type: integer
        errorMessage:
          type: string
        debugInfo:
          type: object
          properties:
            databaseQuery:
              type: string
            userId:
              type: string
            sessionToken:
              type: string

paths:
  /cards:
    post:
      summary: Crear nueva tarjeta
      operationId: createCard
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardRequest'
      responses:
        '200':
          description: Tarjeta creada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardResponse'
        '500':
          description: Error del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                errorCode: 500
                errorMessage: Database connection failed
                debugInfo:
                  databaseQuery: "INSERT INTO cards (customer_id, card_number, cvv, pin) VALUES (?, ?, ?, ?)"
                  userId: "admin@bancoPacifico.com.mx"
                  sessionToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0"

    get:
      summary: Listar todas las tarjetas
      operationId: listCards
      parameters:
        - name: customerId
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Lista de tarjetas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CardResponse'

  /cards/{cardId}:
    get:
      summary: Obtener detalles de tarjeta
      operationId: getCard
      parameters:
        - name: cardId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalles de la tarjeta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardResponse'

  /cards/{cardId}/transactions:
    post:
      summary: Procesar transacción con tarjeta
      operationId: processTransaction
      parameters:
        - name: cardId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequest'
      responses:
        '200':
          description: Transacción procesada
        '400':
          description: Error en la transacción

  /cards/{cardId}/block:
    put:
      summary: Bloquear tarjeta
      operationId: blockCard
      parameters:
        - name: cardId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Tarjeta bloqueada
